=== KlaraKrmpotic/OR_lab_drzave/schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#", 
	"$id": "https://github.com/KlaraKrmpotic/OR_lab_drzave/blob/main/drzave.json", 
	"title": "Root", 
    "description": "10 countries in the world",
	"type": "array",
	"items":{
		"title": "Country", 
        "description": "Country from the list",
		"type": "object",
		"required": [
			"countryid",
			"countryname",
			"isocode",
			"callingcode",
			"currency",
			"language",
			"cities",
			"continent",
			"area",
			"population"
		],
		"properties": {
			"countryid": {
				"title": "Countryid", 
				"type": "integer",
				"examples": [
					1
				]
			},
			"countryname": {
				"title": "Countryname", 
				"type": "string",
				"examples": [
					"Croatia"
				]
			},
			"isocode": {
				"title": "Isocode", 
				"type": "string",
				"examples": [
					"HRV"
				]
			},
			"callingcode": {
				"title": "Callingcode", 
				"type": "integer",
				"examples": [
					385
				]
			},
			"currency": {
				"title": "Currency", 
				"type": "string",
				"examples": [
					"kuna"
				]
			},
			"language": {
				"title": "Language", 
				"type": "string",
				"examples": [
					"Croatian"
				]
			},
			"cities": {
				"title": "Cities", 
				"type": "array",
				"items":{
					"title": "City", 
					"type": "object",
					"required": [
						"cityid",
						"cityname",
						"citypopulation"
					],
					"properties": {
						"cityid": {
							"title": "Cityid", 
							"type": "integer",
							"examples": [
								1
							]
						},
						"cityname": {
							"title": "Cityname", 
							"type": "string",
							"examples": [
								"Zagreb"
							]
						},
						"citypopulation": {
							"title": "Citypopulation", 
							"type": "integer",
							"examples": [
								802338
							]
						}
					}
				}
			},
			"continent": {
				"title": "Continent", 
				"type": "string",
				"examples": [
					"Europe"
				]
			},
			"area": {
				"title": "Area", 
				"type": "integer",
				"examples": [
					56594
				]
			},
			"population": {
				"title": "Population", 
				"type": "integer",
				"examples": [
					4058165
				]
			}
		}
	}
}

=== KlaraKrmpotic/OR_lab_drzave/drzave.json
[
  {
    "countryid": 1,
    "countryname": "Croatia",
    "isocode": "HRV",
    "callingcode": 385,
    "currency": "kuna",
    "language": "Croatian",
    "cities": [
      {
        "cityid": 1,
        "cityname": "Zagreb",
        "citypopulation": 802338
      },
      {
        "cityid": 2,
        "cityname": "Split",
        "citypopulation": 178192
      }
    ],
    "continent": "Europe",
    "area": 56594,
    "population": 4058165
  },
  {
    "countryid": 2,
    "countryname": "United_Kingdom",
    "isocode": "GBR",
    "callingcode": 44,
    "currency": "pound",
    "language": "English",
    "cities": [
      {
        "cityid": 3,
        "cityname": "London",
        "citypopulation": 8961989
      },
      {
        "cityid": 4,
        "cityname": "Manchester",
        "citypopulation": 552858
      }
    ],
    "continent": "Europe",
    "area": 242495,
    "population": 67081000
  },
  {
    "countryid": 3,
    "countryname": "France",
    "isocode": "FRA",
    "callingcode": 33,
    "currency": "euro",
    "language": "French",
    "cities": [
      {
        "cityid": 5,
        "cityname": "Paris",
        "citypopulation": 2175601
      },
      {
        "cityid": 6,
        "cityname": "Marseille",
        "citypopulation": 863310
      }
    ],
    "continent": "Europe",
    "area": 640679,
    "population": 67413000
  },
  {
    "countryid": 4,
    "countryname": "Germany",
    "isocode": "GER",
    "callingcode": 49,
    "currency": "euro",
    "language": "German",
    "cities": [
      {
        "cityid": 7,
        "cityname": "Berlin",
        "citypopulation": 3664088
      },
      {
        "cityid": 8,
        "cityname": "Munich",
        "citypopulation": 1488202
      }
    ],
    "continent": "Europe",
    "area": 357022,
    "population": 83190556
  },
  {
    "countryid": 5,
    "countryname": "Brazil",
    "isocode": "BRA",
    "callingcode": 55,
    "currency": "real",
    "language": "Portugese",
    "cities": [
      {
        "cityid": 9,
        "cityname": "Brasilia",
        "citypopulation": 3094325
      },
      {
        "cityid": 10,
        "cityname": "Sao Paulo",
        "citypopulation": 12396372
      }
    ],
    "continent": "South America",
    "area": 8515767,
    "population": 210147125
  },
  {
    "countryid": 6,
    "countryname": "China",
    "isocode": "CHN",
    "callingcode": 86,
    "currency": "renwinbi",
    "language": "Chinese",
    "cities": [
      {
        "cityid": 11,
        "cityname": "Beijing",
        "citypopulation": 21893095
      },
      {
        "cityid": 12,
        "cityname": "Shanghai",
        "citypopulation": 24870895
      }
    ],
    "continent": "Asia",
    "area": 9596961,
    "population": 1411778724
  },
  {
    "countryid": 7,
    "countryname": "Canada",
    "isocode": "CAN",
    "callingcode": 1,
    "currency": "dollar",
    "language": "English",
    "cities": [
      {
        "cityid": 13,
        "cityname": "Ottawa",
        "citypopulation": 934243
      },
      {
        "cityid": 14,
        "cityname": "Toronto",
        "citypopulation": 2731571
      }
    ],
    "continent": "North America",
    "area": 9984670,
    "population": 38246108
  },
  {
    "countryid": 8,
    "countryname": "Egypt",
    "isocode": "EGY",
    "callingcode": 20,
    "currency": "pound",
    "language": "Arabic",
    "cities": [
      {
        "cityid": 15,
        "cityname": "Cairo",
        "citypopulation": 12230350
      },
      {
        "cityid": 16,
        "cityname": "Giza",
        "citypopulation": 4028062
      }
    ],
    "continent": "Africa",
    "area": 1010408,
    "population": 101478581
  },
  {
    "countryid": 9,
    "countryname": "Japan",
    "isocode": "JPN",
    "callingcode": 81,
    "currency": "yen",
    "language": "Japanese",
    "cities": [
      {
        "cityid": 17,
        "cityname": "Tokyo",
        "citypopulation": 14043239
      },
      {
        "cityid": 18,
        "cityname": "Osaka",
        "citypopulation": 2691185
      }
    ],
    "continent": "Asia",
    "area": 377975,
    "population": 125360000
  },
  {
    "countryid": 10,
    "countryname": "United_States",
    "isocode": "USA",
    "callingcode": 1,
    "currency": "dollar",
    "language": "English",
    "cities": [
      {
        "cityid": 19,
        "cityname": "Washington D.C.",
        "citypopulation": 6385162
      },
      {
        "cityid": 20,
        "cityname": "New York City",
        "citypopulation": 20140470
      }
    ],
    "continent": "North America",
    "area": 9833520,
    "population": 331449281
  }
]
